### PR TITLE
Fixes ts errors and removing refine option changing until search hit

### LINKED ISSUE #133: Word Wheel speed impacted by calls to Search with each keypress
Currently, when you type in the fields, it sends both a word wheel search, and a fulltext search to the server.  

Calling the server to get facets with fewer than 4 or 5 characters typed is not really a good use of resources, and it slows down the performance of the word wheel, making it less useful unless you are a hunt and peck typist.

The facets aren't really needed until you either press Search, enter a "space" to start a second word, or pause typing for 1 or 2 seconds.  It's very nice to have the facets once you enter a real word, even if you plan to enter a second or third, but not much use with a partial word.

To experiment with this, I've set the server to return a 422 error if you send a search with less than 5 characters.  I don't think we have **important** words of 4 characters, but really, that's not the right way to implement the restriction anyway.

Thus, I would like you to implement this in the client.  That way, you can send word wheel but not full-text searches for the first 3 or 4 characters, and then if, for whatever reason, the user does enter a three letter word and presses "Search", it will be executed (after I remove the restriction.)  But I wanted to try it to check whether the word wheel works better, and I think it does.

### PR DESCRIPTION
**Pull request by bakerac4**
Fixes #133

### CODE REVIEW

File: pep/app/pods/most-cited-loading/route.ts [hunk 1]
```diff
@@ -1,7 +1,10 @@
 import Route from '@ember/routing/route';
+
 import { PageNav } from 'pep/mixins/page-layout';
 
 export default class MostCitedLoading extends PageNav(Route) {
     navController = 'most-cited';
-    navTemplate = 'most-cited/nav';
+    get navTemplate() {
+        return 'most-cited/nav';
+    }
```
Comment (billdami) [inline pep/app/pods/most-cited-loading/route.ts:9]: why is this needed for navTemplate but not navController?

Comment (bakerac4) [reply pep/app/pods/most-cited-loading/route.ts:9]: It's due to how navTemplate is defined in the function. `navController` is a property and `navTemplate` is a getter

**Review by billdami — APPROVED** [review]
