### PR TITLE
Multiple fixes

### LINKED ISSUE #256: Hit Summary - Link at top
1) The hit summary/link at top always has the words munged together.

image

2) If there's only one hit, and you go to it, then scroll around the document, the link is no longer available at the top:

image

### PR DESCRIPTION
**Pull request by bakerac4**
Fixes #256, #255, Part of #254, #239, #220

@nrshapiro in order to fully fix 254, I need more information. See https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/issues/254#issuecomment-768350239

### CODE REVIEW

File: pep/app/pods/search/read/controller.ts [hunk 1]
```diff
@@ -218,6 +218,18 @@ export default class SearchRead extends Controller {
...
+    /**
+     * Set the search hit number to the next number. Most likely its the same number they were on, so make it undefined first
+     *
+     * @param {number} number
+     * @memberof SearchRead
+     */
+    @action
+    viewSearchHitNumber(number: number) {
+        this.searchHitNumber = undefined;
+        this.searchHitNumber = number;
```
Comment (billdami) [inline pep/app/pods/search/read/controller.ts:231]: I dont _think_ this will have any actual effect on ember/glimmer, as it waits until the end of the runloop to coalesce all value changes before a new render. its more likely in these cases you want to do something like:
```ts
this.searchHitNumber = undefined;
next(this, () => this.searchHitNumber = number);
```

**Review by billdami — APPROVED** [review]
